#!/bin/bash

sudo puppet resource package apache2 ensure=installed
sudo puppet resource service apache2 ensure=running

sudo rm -rf /tmp/work/8363488a
sudo mkdir -p /tmp/work/8363488a

sudo git clone https://github.com/MunSka/app-8363488a-repo.git /tmp/work/8363488a

sudo cp /tmp/work/8363488a/new_8363488a_index.html /var/www/html/index.html
sudo chown www-data:www-data /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
